# Project: 房产销售系统
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = guest.o main.o sold.o source.o
LINKOBJ  = guest.o main.o sold.o source.o
LIBS     = -L"G:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"G:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 房产销售系统.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

guest.o: guest.cpp
	$(CPP) -c guest.cpp -o guest.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

sold.o: sold.cpp
	$(CPP) -c sold.cpp -o sold.o $(CXXFLAGS)

source.o: source.cpp
	$(CPP) -c source.cpp -o source.o $(CXXFLAGS)
